[package]

name = "skia"
version = "0.0.20130412"
authors = ["The Skia Project Developers and The Servo Project Developers"]
links = "skia"
build = "build.rs"

[dependencies.freetype-sys]
git = "https://github.com/servo/libfreetype2"

[dependencies.expat-sys]
git = "https://github.com/servo/libexpat"

