[package]

name = "skia-sys"
version = "0.0.20130412"
authors = ["The Skia Project Developers"]

build = "make -f makefile.cargo -j4"

[lib]

name = "skia-sys"
path = "lib.rs"

[dependencies.freetype-sys]
git = "https://github.com/servo/libfreetype2"

[dependencies.expat-sys]
git = "https://github.com/servo/libexpat"

